### ISSUE TITLE
Unable to get working with 3.2.7 etcd

### ISSUE THREAD

**Issue by RaunoVV** [lclarkmichalek/etcdhcp#3]
Hi,

Just trying it out and seems like awesome piece but having some troubles getting it to work properly. When I start it it loads up and fills etcd with free ip's. But when some virtual machine tries to connect it then it generates a error: 
```
dhcp.go:55] could not lease: could not update lease: could not update for leased ip: etcdserver: key not found
```

Any ideas?

etcd 3.2.7
etcdhcp master

**Comment by lclarkmichalek** [comment]
We use multikey transactions, so only works with >3.3.0, sorry :)
